name: "Dev_Account_Plan"

on:
  push:
    branches:
      - 'feature/*'

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - id: auth 
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/316933479822/locations/global/workloadIdentityPools/github-actions/providers/github'
          service_account: 'iaac-sa@model-hexagon-351804.iam.gserviceaccount.com'
          token_format: 'access_token'

      - id: 'listbuckets'
        run: |-
          curl https://storage.googleapis.com/storage/v1/b/us-terraform-state-file-bucket-7482/o \
          --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=us-terraform-state-file-bucket-7482" -backend-config="prefix=account/dev"
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color -var-file="develop.auto.tfvars"