name: "QA_Account_Plan_Apply"

on:

on:
  push:
    branches:
      - qa

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: workload_identity_provider
    permissions:
      id-token: write
      contents: read

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - id: auth 
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SA_EMAIL }}
          token_format: 'access_token'

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=us-terraform-state-file-bucket-7482" -backend-config="prefix=account/qa"

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color -var-file="qa.auto.tfvars"
        continue-on-error: true

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform apply -var-file="qa.auto.tfvars" --auto-approve 
        
      - name: Terraform Destroy
        run: terraform destroy -var-file="qa.auto.tfvars" --auto-approve
